export const CONTACT_INFORMATION: string[] = [
  'BVKZ.CONTACT__COMPONENT.CONTACT__LEADER_NAME',
  'BVKZ.CONTACT__COMPONENT.CONTACT__EMAIL_ADDRESS',
  'BVKZ.CONTACT__COMPONENT.CONTACT__ADDRESS',
];
